---
- name: "Start by install Docker"
  register: output
  changed_when: output.rc != 0
  ansible.builtin.shell: |
    curl https://releases.rancher.com/install-docker/{{ install_kubernetes_cluster_docker_script_version }}.sh | sh

- name: "Init the cluster"
  run_once: yes
  when: install_kubernetes_cluster_is_manager | default(false)
  block:
    - name: "Init the cluster with the command line shell"
      register: output
      changed_when: output.rc != 0
      ansible.builtin.shell:
        curl -sfL https://get.k3s.io | sh -s - \
        --docker \
        --data-dir {{ install_kubernetes_cluster_data_dir }} \
        --cluster-cidr {{ install_kubernetes_cluster_cluster_cidr }} \
        --service-cidr {{ install_kubernetes_cluster_service_cidr }} \
        --service-node-port-range {{ install_kubernetes_cluster_service_node_port_range }} \
        --cluster-dns {{ install_kubernetes_cluster_cluster_dns }} \
        --cluster-domain {{ install_kubernetes_cluster_cluster_domain }}

    - name: "Check if server is initialized"
      register: result
      until: "result.status == 403"
      retries: 5
      delay: 5
      ansible.builtin.uri:
        url: "https://{{ inventory_hostname }}:6443"
        validate_certs: no
        status_code: [403]

    - name: "Get the join token"
      register: output
      changed_when: output.rc != 0
      ansible.builtin.shell:
        cat /var/lib/rancher/k3s/server/node-token

    - name: "Set facts"
      ansible.legacy.set_fact:
        join_token: "{{ token_output.stdout }}"
        server_node: "{{ inventory_hostname }}"