---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.add_kubernetes_cluster"
      tags:
        - "labocbz.add_kubernetes_cluster"
      vars:
        add_kubernetes_cluster_is_manager: "{{ inv_add_kubernetes_cluster_is_manager }}"
        add_kubernetes_cluster_advertise_address: "{{ inv_add_kubernetes_cluster_advertise_address }}"
        add_kubernetes_cluster_cert_sans: "{{ inv_add_kubernetes_cluster_cert_sans }}"
        add_kubernetes_cluster_cert_dir: "{{ inv_add_kubernetes_cluster_cert_dir }}"
        add_kubernetes_cluster_node_name: "{{ inv_add_kubernetes_cluster_node_name }}"
        add_kubernetes_cluster_network_cidr: "{{ inv_add_kubernetes_cluster_network_cidr }}"
        add_kubernetes_cluster_service_cidr: "{{ inv_add_kubernetes_cluster_service_cidr }}"
        add_kubernetes_cluster_control_plane_endpoint: "{{ inv_add_kubernetes_cluster_control_plane_endpoint }}"
        add_kubernetes_cluster_service_dns: "{{ inv_add_kubernetes_cluster_service_dns }}"
      ansible.builtin.include_role:
        name: "labocbz.add_kubernetes_cluster"
