---
- name: "Converge"
  hosts: "cicd-docker-dind"
  tasks:

    - name: "Include labocbz.install_kubernetes_cluster"
      tags:
        - "labocbz.install_kubernetes_cluster"
      vars:
        install_kubernetes_cluster__is_manager: "{{ inv_install_kubernetes_cluster__is_manager }}"
        install_kubernetes_cluster__docker_script_version: "{{ inv_install_kubernetes_cluster__docker_script_version }}"
        install_kubernetes_cluster__data_dir: "{{ inv_install_kubernetes_cluster__data_dir }}"
        install_kubernetes_cluster__cluster_cidr: "{{ inv_install_kubernetes_cluster__cluster_cidr }}"
        install_kubernetes_cluster__service_cidr: "{{ inv_install_kubernetes_cluster__service_cidr }}"
        install_kubernetes_cluster__service_node_port_range: "{{ inv_install_kubernetes_cluster__service_node_port_range }}"
        install_kubernetes_cluster__cluster_dns: "{{ inv_install_kubernetes_cluster__cluster_dns }}"
        install_kubernetes_cluster__cluster_domain: "{{ inv_install_kubernetes_cluster__cluster_domain }}"
        install_kubernetes_cluster__tls_sans: "{{ inv_install_kubernetes_cluster__tls_sans }}"
      ansible.builtin.include_role:
        name: "labocbz.install_kubernetes_cluster"
