---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "cicd-docker-dind"
  gather_facts: false
  tasks:

    - name: "Check docker-compose command response"
      register: output
      changed_when: output.rc != 0
      failed_when: output.rc != 0
      ansible.builtin.command: "docker -v"

    - name: "Check docker-compose command response"
      register: output
      changed_when: output.rc != 0
      failed_when: output.rc != 0
      ansible.builtin.command: "docker-compose -v"

    - name: "Check API HTTPS URL"
      register: result
      failed_when: result.status != 401
      when: inv_install_kubernetes_cluster__is_manager | default(false)
      ansible.builtin.uri:
        validate_certs: no
        url: "https://{{ inventory_hostname }}:6443/"
        method: "GET"
        status_code: [401]

    - name: "Check k3s kubectl get nodes command response"
      register: output
      failed_when: output.rc != 0
      when: inv_install_kubernetes_cluster__is_manager | default(false)
      ansible.builtin.command: "k3s kubectl get nodes"

    - name: "Checkkubectl get pods --all-namespaces command response"
      register: output
      failed_when: output.rc != 0
      when: inv_install_kubernetes_cluster__is_manager | default(false)
      ansible.builtin.command: "kubectl get pods --all-namespaces"
